# Generated by Django 5.2.7 on 2025-10-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("endereco", models.CharField(blank=True, max_length=255)),
                ("data_nascimento", models.CharField(blank=True, null=True)),
            ],
        ),
    ]
