# Generated by Django 5.2.7 on 2025-10-26 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_transicao', models.DateField(auto_now_add=True)),
                ('metodo_pagamento', models.CharField(max_length=100)),
                ('cobranca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cobranca')),
            ],
        ),
    ]
