# Generated by Django 5.2.7 on 2025-10-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tempo_estimado', models.DurationField(help_text="Tempo estimado para o procedimento. Ex: '1:30:00' para 1h 30min.")),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
