# Generated by Django 5.2.7 on 2025-10-14 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_procedimento"),
        ("api", "0002_veiculo"),
    ]

    operations = []
