# Generated by Django 5.2.7 on 2025-10-31 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_pagamento_cobranca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='cliente',
        ),
    ]
