# Generated by Django 5.2.7 on 2025-10-18 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_insumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsumoOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.insumo')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ordemservico')),
            ],
            options={
                'unique_together': {('ordem_servico', 'insumo')},
            },
        ),
    ]
