# Generated by Django 5.2.7 on 2025-10-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_insumoordemservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='insumos',
            field=models.ManyToManyField(related_name='ordens_de_servico', through='api.InsumoOrdemServico', to='api.insumo'),
        ),
    ]
