# Generated by Django 5.2.7 on 2025-10-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ordemservico_insumos'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='procedimentos',
            field=models.ManyToManyField(to='api.procedimento'),
        ),
    ]
